/* SPDX-License-Identifier: GPL-3.0-or-later; Copyright (C) 2026 Tablelight contributors. */
'use strict';
module.exports = {
  appId: 'io.github.rouster67.tablelight',
  productName: 'Tablelight',
  // Preserve the project's existing distribution of editable application source.
  asar: false,
  npmRebuild: false,
  directories: { output: 'dist', buildResources: 'build' },
  files: [
    '*.js',
    '*.html',
    '*.css',
    'icon.png',
    'package.json',
    'package-lock.json',
    'LICENSE',
    'LICENSE.electron.txt',
    'NOTICE.md',
    'THIRD_PARTY_NOTICES.md',
    'README.md',
    'CHANGELOG.md',
    'CONTRIBUTING.md',
    'SECURITY.md',
    'docs/**/*',
    'scripts/**/*',
    'tests/**/*',
    '.github/**/*',
    'build/**/*',
    'electron-builder.cjs',
    '.gitignore',
    '.gitattributes',
    '.editorconfig',
    '.prettierrc.json',
    '.prettierignore',
  ],
  extraFiles: [
    { from: 'docs/USER_GUIDE.md', to: 'START HERE.md' },
    { from: 'LICENSE', to: 'LICENSE.Tablelight.txt' },
    { from: 'NOTICE.md', to: 'NOTICE.Tablelight.md' },
    { from: 'THIRD_PARTY_NOTICES.md', to: 'THIRD_PARTY_NOTICES.md' },
  ],
  afterPack: 'build/after-pack.cjs',
  beforePack: 'build/before-pack.cjs',
  win: { target: 'nsis', icon: 'icon.png', requestedExecutionLevel: 'asInvoker' },
  nsis: {
    oneClick: false,
    perMachine: false,
    allowElevation: false,
    allowToChangeInstallationDirectory: true,
    deleteAppDataOnUninstall: false,
    include: 'build/installer.nsh',
    artifactName: 'Tablelight-Setup-${version}-${arch}.${ext}',
    shortcutName: 'Tablelight',
    uninstallDisplayName: 'Tablelight',
  },
  publish: [{ provider: 'github', owner: 'Rouster67', repo: 'Tablelight', releaseType: 'release' }],
};
